apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcatcicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcatcicd
  template:
    metadata:
      labels:
        app: tomcatcicd
    spec:
      containers:
      - name: webapp
        image: rishabh0409/cicd
        
---


apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: tomcatcicd
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
